// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reads.proto

#ifndef PROTOBUF_Reads_2eproto__INCLUDED
#define PROTOBUF_Reads_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace goby {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Reads_2eproto();
void protobuf_AssignDesc_Reads_2eproto();
void protobuf_ShutdownFile_Reads_2eproto();

class MetaData;
class ReadCollection;
class ReadEntry;

// ===================================================================

class ReadCollection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:goby.ReadCollection) */ {
 public:
  ReadCollection();
  virtual ~ReadCollection();

  ReadCollection(const ReadCollection& from);

  inline ReadCollection& operator=(const ReadCollection& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadCollection& default_instance();

  void Swap(ReadCollection* other);

  // implements Message ----------------------------------------------

  inline ReadCollection* New() const { return New(NULL); }

  ReadCollection* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReadCollection& from);
  void MergeFrom(const ReadCollection& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ReadCollection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .goby.ReadEntry reads = 1;
  int reads_size() const;
  void clear_reads();
  static const int kReadsFieldNumber = 1;
  const ::goby::ReadEntry& reads(int index) const;
  ::goby::ReadEntry* mutable_reads(int index);
  ::goby::ReadEntry* add_reads();
  ::google::protobuf::RepeatedPtrField< ::goby::ReadEntry >*
      mutable_reads();
  const ::google::protobuf::RepeatedPtrField< ::goby::ReadEntry >&
      reads() const;

  // @@protoc_insertion_point(class_scope:goby.ReadCollection)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::goby::ReadEntry > reads_;
  friend void  protobuf_AddDesc_Reads_2eproto();
  friend void protobuf_AssignDesc_Reads_2eproto();
  friend void protobuf_ShutdownFile_Reads_2eproto();

  void InitAsDefaultInstance();
  static ReadCollection* default_instance_;
};
// -------------------------------------------------------------------

class ReadEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:goby.ReadEntry) */ {
 public:
  ReadEntry();
  virtual ~ReadEntry();

  ReadEntry(const ReadEntry& from);

  inline ReadEntry& operator=(const ReadEntry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ReadEntry& default_instance();

  void Swap(ReadEntry* other);

  // implements Message ----------------------------------------------

  inline ReadEntry* New() const { return New(NULL); }

  ReadEntry* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReadEntry& from);
  void MergeFrom(const ReadEntry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ReadEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 read_index = 1;
  bool has_read_index() const;
  void clear_read_index();
  static const int kReadIndexFieldNumber = 1;
  ::google::protobuf::uint32 read_index() const;
  void set_read_index(::google::protobuf::uint32 value);

  // optional uint32 barcode_index = 10;
  bool has_barcode_index() const;
  void clear_barcode_index();
  static const int kBarcodeIndexFieldNumber = 10;
  ::google::protobuf::uint32 barcode_index() const;
  void set_barcode_index(::google::protobuf::uint32 value);

  // optional string read_identifier = 23;
  bool has_read_identifier() const;
  void clear_read_identifier();
  static const int kReadIdentifierFieldNumber = 23;
  const ::std::string& read_identifier() const;
  void set_read_identifier(const ::std::string& value);
  void set_read_identifier(const char* value);
  void set_read_identifier(const char* value, size_t size);
  ::std::string* mutable_read_identifier();
  ::std::string* release_read_identifier();
  void set_allocated_read_identifier(::std::string* read_identifier);

  // optional string description = 22;
  bool has_description() const;
  void clear_description();
  static const int kDescriptionFieldNumber = 22;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // required uint32 read_length = 2;
  bool has_read_length() const;
  void clear_read_length();
  static const int kReadLengthFieldNumber = 2;
  ::google::protobuf::uint32 read_length() const;
  void set_read_length(::google::protobuf::uint32 value);

  // optional bytes sequence = 3;
  bool has_sequence() const;
  void clear_sequence();
  static const int kSequenceFieldNumber = 3;
  const ::std::string& sequence() const;
  void set_sequence(const ::std::string& value);
  void set_sequence(const char* value);
  void set_sequence(const void* value, size_t size);
  ::std::string* mutable_sequence();
  ::std::string* release_sequence();
  void set_allocated_sequence(::std::string* sequence);

  // optional bytes sequence_pair = 5;
  bool has_sequence_pair() const;
  void clear_sequence_pair();
  static const int kSequencePairFieldNumber = 5;
  const ::std::string& sequence_pair() const;
  void set_sequence_pair(const ::std::string& value);
  void set_sequence_pair(const char* value);
  void set_sequence_pair(const void* value, size_t size);
  ::std::string* mutable_sequence_pair();
  ::std::string* release_sequence_pair();
  void set_allocated_sequence_pair(::std::string* sequence_pair);

  // optional uint32 read_length_pair = 6;
  bool has_read_length_pair() const;
  void clear_read_length_pair();
  static const int kReadLengthPairFieldNumber = 6;
  ::google::protobuf::uint32 read_length_pair() const;
  void set_read_length_pair(::google::protobuf::uint32 value);

  // optional bytes quality_scores = 4;
  bool has_quality_scores() const;
  void clear_quality_scores();
  static const int kQualityScoresFieldNumber = 4;
  const ::std::string& quality_scores() const;
  void set_quality_scores(const ::std::string& value);
  void set_quality_scores(const char* value);
  void set_quality_scores(const void* value, size_t size);
  ::std::string* mutable_quality_scores();
  ::std::string* release_quality_scores();
  void set_allocated_quality_scores(::std::string* quality_scores);

  // optional bytes quality_scores_pair = 7;
  bool has_quality_scores_pair() const;
  void clear_quality_scores_pair();
  static const int kQualityScoresPairFieldNumber = 7;
  const ::std::string& quality_scores_pair() const;
  void set_quality_scores_pair(const ::std::string& value);
  void set_quality_scores_pair(const char* value);
  void set_quality_scores_pair(const void* value, size_t size);
  ::std::string* mutable_quality_scores_pair();
  ::std::string* release_quality_scores_pair();
  void set_allocated_quality_scores_pair(::std::string* quality_scores_pair);

  // optional bytes compressed_data = 8;
  bool has_compressed_data() const;
  void clear_compressed_data();
  static const int kCompressedDataFieldNumber = 8;
  const ::std::string& compressed_data() const;
  void set_compressed_data(const ::std::string& value);
  void set_compressed_data(const char* value);
  void set_compressed_data(const void* value, size_t size);
  ::std::string* mutable_compressed_data();
  ::std::string* release_compressed_data();
  void set_allocated_compressed_data(::std::string* compressed_data);

  // repeated .goby.MetaData meta_data = 25;
  int meta_data_size() const;
  void clear_meta_data();
  static const int kMetaDataFieldNumber = 25;
  const ::goby::MetaData& meta_data(int index) const;
  ::goby::MetaData* mutable_meta_data(int index);
  ::goby::MetaData* add_meta_data();
  ::google::protobuf::RepeatedPtrField< ::goby::MetaData >*
      mutable_meta_data();
  const ::google::protobuf::RepeatedPtrField< ::goby::MetaData >&
      meta_data() const;

  // @@protoc_insertion_point(class_scope:goby.ReadEntry)
 private:
  inline void set_has_read_index();
  inline void clear_has_read_index();
  inline void set_has_barcode_index();
  inline void clear_has_barcode_index();
  inline void set_has_read_identifier();
  inline void clear_has_read_identifier();
  inline void set_has_description();
  inline void clear_has_description();
  inline void set_has_read_length();
  inline void clear_has_read_length();
  inline void set_has_sequence();
  inline void clear_has_sequence();
  inline void set_has_sequence_pair();
  inline void clear_has_sequence_pair();
  inline void set_has_read_length_pair();
  inline void clear_has_read_length_pair();
  inline void set_has_quality_scores();
  inline void clear_has_quality_scores();
  inline void set_has_quality_scores_pair();
  inline void clear_has_quality_scores_pair();
  inline void set_has_compressed_data();
  inline void clear_has_compressed_data();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 read_index_;
  ::google::protobuf::uint32 barcode_index_;
  ::google::protobuf::internal::ArenaStringPtr read_identifier_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::internal::ArenaStringPtr sequence_;
  ::google::protobuf::uint32 read_length_;
  ::google::protobuf::uint32 read_length_pair_;
  ::google::protobuf::internal::ArenaStringPtr sequence_pair_;
  ::google::protobuf::internal::ArenaStringPtr quality_scores_;
  ::google::protobuf::internal::ArenaStringPtr quality_scores_pair_;
  ::google::protobuf::internal::ArenaStringPtr compressed_data_;
  ::google::protobuf::RepeatedPtrField< ::goby::MetaData > meta_data_;
  friend void  protobuf_AddDesc_Reads_2eproto();
  friend void protobuf_AssignDesc_Reads_2eproto();
  friend void protobuf_ShutdownFile_Reads_2eproto();

  void InitAsDefaultInstance();
  static ReadEntry* default_instance_;
};
// -------------------------------------------------------------------

class MetaData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:goby.MetaData) */ {
 public:
  MetaData();
  virtual ~MetaData();

  MetaData(const MetaData& from);

  inline MetaData& operator=(const MetaData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MetaData& default_instance();

  void Swap(MetaData* other);

  // implements Message ----------------------------------------------

  inline MetaData* New() const { return New(NULL); }

  MetaData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MetaData& from);
  void MergeFrom(const MetaData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MetaData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string key = 1;
  bool has_key() const;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // required string value = 2;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:goby.MetaData)
 private:
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_value();
  inline void clear_has_value();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  friend void  protobuf_AddDesc_Reads_2eproto();
  friend void protobuf_AssignDesc_Reads_2eproto();
  friend void protobuf_ShutdownFile_Reads_2eproto();

  void InitAsDefaultInstance();
  static MetaData* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ReadCollection

// repeated .goby.ReadEntry reads = 1;
inline int ReadCollection::reads_size() const {
  return reads_.size();
}
inline void ReadCollection::clear_reads() {
  reads_.Clear();
}
inline const ::goby::ReadEntry& ReadCollection::reads(int index) const {
  // @@protoc_insertion_point(field_get:goby.ReadCollection.reads)
  return reads_.Get(index);
}
inline ::goby::ReadEntry* ReadCollection::mutable_reads(int index) {
  // @@protoc_insertion_point(field_mutable:goby.ReadCollection.reads)
  return reads_.Mutable(index);
}
inline ::goby::ReadEntry* ReadCollection::add_reads() {
  // @@protoc_insertion_point(field_add:goby.ReadCollection.reads)
  return reads_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::goby::ReadEntry >*
ReadCollection::mutable_reads() {
  // @@protoc_insertion_point(field_mutable_list:goby.ReadCollection.reads)
  return &reads_;
}
inline const ::google::protobuf::RepeatedPtrField< ::goby::ReadEntry >&
ReadCollection::reads() const {
  // @@protoc_insertion_point(field_list:goby.ReadCollection.reads)
  return reads_;
}

// -------------------------------------------------------------------

// ReadEntry

// required uint32 read_index = 1;
inline bool ReadEntry::has_read_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ReadEntry::set_has_read_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ReadEntry::clear_has_read_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ReadEntry::clear_read_index() {
  read_index_ = 0u;
  clear_has_read_index();
}
inline ::google::protobuf::uint32 ReadEntry::read_index() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.read_index)
  return read_index_;
}
inline void ReadEntry::set_read_index(::google::protobuf::uint32 value) {
  set_has_read_index();
  read_index_ = value;
  // @@protoc_insertion_point(field_set:goby.ReadEntry.read_index)
}

// optional uint32 barcode_index = 10;
inline bool ReadEntry::has_barcode_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ReadEntry::set_has_barcode_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ReadEntry::clear_has_barcode_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ReadEntry::clear_barcode_index() {
  barcode_index_ = 0u;
  clear_has_barcode_index();
}
inline ::google::protobuf::uint32 ReadEntry::barcode_index() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.barcode_index)
  return barcode_index_;
}
inline void ReadEntry::set_barcode_index(::google::protobuf::uint32 value) {
  set_has_barcode_index();
  barcode_index_ = value;
  // @@protoc_insertion_point(field_set:goby.ReadEntry.barcode_index)
}

// optional string read_identifier = 23;
inline bool ReadEntry::has_read_identifier() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ReadEntry::set_has_read_identifier() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ReadEntry::clear_has_read_identifier() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ReadEntry::clear_read_identifier() {
  read_identifier_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_read_identifier();
}
inline const ::std::string& ReadEntry::read_identifier() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.read_identifier)
  return read_identifier_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_read_identifier(const ::std::string& value) {
  set_has_read_identifier();
  read_identifier_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.read_identifier)
}
inline void ReadEntry::set_read_identifier(const char* value) {
  set_has_read_identifier();
  read_identifier_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.read_identifier)
}
inline void ReadEntry::set_read_identifier(const char* value, size_t size) {
  set_has_read_identifier();
  read_identifier_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.read_identifier)
}
inline ::std::string* ReadEntry::mutable_read_identifier() {
  set_has_read_identifier();
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.read_identifier)
  return read_identifier_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReadEntry::release_read_identifier() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.read_identifier)
  clear_has_read_identifier();
  return read_identifier_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_read_identifier(::std::string* read_identifier) {
  if (read_identifier != NULL) {
    set_has_read_identifier();
  } else {
    clear_has_read_identifier();
  }
  read_identifier_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), read_identifier);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.read_identifier)
}

// optional string description = 22;
inline bool ReadEntry::has_description() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ReadEntry::set_has_description() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ReadEntry::clear_has_description() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ReadEntry::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_description();
}
inline const ::std::string& ReadEntry::description() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.description)
  return description_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_description(const ::std::string& value) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.description)
}
inline void ReadEntry::set_description(const char* value) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.description)
}
inline void ReadEntry::set_description(const char* value, size_t size) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.description)
}
inline ::std::string* ReadEntry::mutable_description() {
  set_has_description();
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReadEntry::release_description() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.description)
  clear_has_description();
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    set_has_description();
  } else {
    clear_has_description();
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.description)
}

// required uint32 read_length = 2;
inline bool ReadEntry::has_read_length() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ReadEntry::set_has_read_length() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ReadEntry::clear_has_read_length() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ReadEntry::clear_read_length() {
  read_length_ = 0u;
  clear_has_read_length();
}
inline ::google::protobuf::uint32 ReadEntry::read_length() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.read_length)
  return read_length_;
}
inline void ReadEntry::set_read_length(::google::protobuf::uint32 value) {
  set_has_read_length();
  read_length_ = value;
  // @@protoc_insertion_point(field_set:goby.ReadEntry.read_length)
}

// optional bytes sequence = 3;
inline bool ReadEntry::has_sequence() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ReadEntry::set_has_sequence() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ReadEntry::clear_has_sequence() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ReadEntry::clear_sequence() {
  sequence_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sequence();
}
inline const ::std::string& ReadEntry::sequence() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.sequence)
  return sequence_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_sequence(const ::std::string& value) {
  set_has_sequence();
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.sequence)
}
inline void ReadEntry::set_sequence(const char* value) {
  set_has_sequence();
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.sequence)
}
inline void ReadEntry::set_sequence(const void* value, size_t size) {
  set_has_sequence();
  sequence_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.sequence)
}
inline ::std::string* ReadEntry::mutable_sequence() {
  set_has_sequence();
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.sequence)
  return sequence_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReadEntry::release_sequence() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.sequence)
  clear_has_sequence();
  return sequence_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_sequence(::std::string* sequence) {
  if (sequence != NULL) {
    set_has_sequence();
  } else {
    clear_has_sequence();
  }
  sequence_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sequence);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.sequence)
}

// optional bytes sequence_pair = 5;
inline bool ReadEntry::has_sequence_pair() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ReadEntry::set_has_sequence_pair() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ReadEntry::clear_has_sequence_pair() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ReadEntry::clear_sequence_pair() {
  sequence_pair_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sequence_pair();
}
inline const ::std::string& ReadEntry::sequence_pair() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.sequence_pair)
  return sequence_pair_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_sequence_pair(const ::std::string& value) {
  set_has_sequence_pair();
  sequence_pair_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.sequence_pair)
}
inline void ReadEntry::set_sequence_pair(const char* value) {
  set_has_sequence_pair();
  sequence_pair_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.sequence_pair)
}
inline void ReadEntry::set_sequence_pair(const void* value, size_t size) {
  set_has_sequence_pair();
  sequence_pair_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.sequence_pair)
}
inline ::std::string* ReadEntry::mutable_sequence_pair() {
  set_has_sequence_pair();
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.sequence_pair)
  return sequence_pair_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReadEntry::release_sequence_pair() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.sequence_pair)
  clear_has_sequence_pair();
  return sequence_pair_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_sequence_pair(::std::string* sequence_pair) {
  if (sequence_pair != NULL) {
    set_has_sequence_pair();
  } else {
    clear_has_sequence_pair();
  }
  sequence_pair_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sequence_pair);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.sequence_pair)
}

// optional uint32 read_length_pair = 6;
inline bool ReadEntry::has_read_length_pair() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ReadEntry::set_has_read_length_pair() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ReadEntry::clear_has_read_length_pair() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ReadEntry::clear_read_length_pair() {
  read_length_pair_ = 0u;
  clear_has_read_length_pair();
}
inline ::google::protobuf::uint32 ReadEntry::read_length_pair() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.read_length_pair)
  return read_length_pair_;
}
inline void ReadEntry::set_read_length_pair(::google::protobuf::uint32 value) {
  set_has_read_length_pair();
  read_length_pair_ = value;
  // @@protoc_insertion_point(field_set:goby.ReadEntry.read_length_pair)
}

// optional bytes quality_scores = 4;
inline bool ReadEntry::has_quality_scores() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ReadEntry::set_has_quality_scores() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ReadEntry::clear_has_quality_scores() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ReadEntry::clear_quality_scores() {
  quality_scores_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_quality_scores();
}
inline const ::std::string& ReadEntry::quality_scores() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.quality_scores)
  return quality_scores_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_quality_scores(const ::std::string& value) {
  set_has_quality_scores();
  quality_scores_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.quality_scores)
}
inline void ReadEntry::set_quality_scores(const char* value) {
  set_has_quality_scores();
  quality_scores_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.quality_scores)
}
inline void ReadEntry::set_quality_scores(const void* value, size_t size) {
  set_has_quality_scores();
  quality_scores_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.quality_scores)
}
inline ::std::string* ReadEntry::mutable_quality_scores() {
  set_has_quality_scores();
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.quality_scores)
  return quality_scores_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReadEntry::release_quality_scores() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.quality_scores)
  clear_has_quality_scores();
  return quality_scores_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_quality_scores(::std::string* quality_scores) {
  if (quality_scores != NULL) {
    set_has_quality_scores();
  } else {
    clear_has_quality_scores();
  }
  quality_scores_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), quality_scores);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.quality_scores)
}

// optional bytes quality_scores_pair = 7;
inline bool ReadEntry::has_quality_scores_pair() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void ReadEntry::set_has_quality_scores_pair() {
  _has_bits_[0] |= 0x00000200u;
}
inline void ReadEntry::clear_has_quality_scores_pair() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void ReadEntry::clear_quality_scores_pair() {
  quality_scores_pair_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_quality_scores_pair();
}
inline const ::std::string& ReadEntry::quality_scores_pair() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.quality_scores_pair)
  return quality_scores_pair_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_quality_scores_pair(const ::std::string& value) {
  set_has_quality_scores_pair();
  quality_scores_pair_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.quality_scores_pair)
}
inline void ReadEntry::set_quality_scores_pair(const char* value) {
  set_has_quality_scores_pair();
  quality_scores_pair_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.quality_scores_pair)
}
inline void ReadEntry::set_quality_scores_pair(const void* value, size_t size) {
  set_has_quality_scores_pair();
  quality_scores_pair_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.quality_scores_pair)
}
inline ::std::string* ReadEntry::mutable_quality_scores_pair() {
  set_has_quality_scores_pair();
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.quality_scores_pair)
  return quality_scores_pair_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReadEntry::release_quality_scores_pair() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.quality_scores_pair)
  clear_has_quality_scores_pair();
  return quality_scores_pair_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_quality_scores_pair(::std::string* quality_scores_pair) {
  if (quality_scores_pair != NULL) {
    set_has_quality_scores_pair();
  } else {
    clear_has_quality_scores_pair();
  }
  quality_scores_pair_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), quality_scores_pair);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.quality_scores_pair)
}

// optional bytes compressed_data = 8;
inline bool ReadEntry::has_compressed_data() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void ReadEntry::set_has_compressed_data() {
  _has_bits_[0] |= 0x00000400u;
}
inline void ReadEntry::clear_has_compressed_data() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void ReadEntry::clear_compressed_data() {
  compressed_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_compressed_data();
}
inline const ::std::string& ReadEntry::compressed_data() const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.compressed_data)
  return compressed_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_compressed_data(const ::std::string& value) {
  set_has_compressed_data();
  compressed_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.ReadEntry.compressed_data)
}
inline void ReadEntry::set_compressed_data(const char* value) {
  set_has_compressed_data();
  compressed_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.ReadEntry.compressed_data)
}
inline void ReadEntry::set_compressed_data(const void* value, size_t size) {
  set_has_compressed_data();
  compressed_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.ReadEntry.compressed_data)
}
inline ::std::string* ReadEntry::mutable_compressed_data() {
  set_has_compressed_data();
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.compressed_data)
  return compressed_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ReadEntry::release_compressed_data() {
  // @@protoc_insertion_point(field_release:goby.ReadEntry.compressed_data)
  clear_has_compressed_data();
  return compressed_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ReadEntry::set_allocated_compressed_data(::std::string* compressed_data) {
  if (compressed_data != NULL) {
    set_has_compressed_data();
  } else {
    clear_has_compressed_data();
  }
  compressed_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), compressed_data);
  // @@protoc_insertion_point(field_set_allocated:goby.ReadEntry.compressed_data)
}

// repeated .goby.MetaData meta_data = 25;
inline int ReadEntry::meta_data_size() const {
  return meta_data_.size();
}
inline void ReadEntry::clear_meta_data() {
  meta_data_.Clear();
}
inline const ::goby::MetaData& ReadEntry::meta_data(int index) const {
  // @@protoc_insertion_point(field_get:goby.ReadEntry.meta_data)
  return meta_data_.Get(index);
}
inline ::goby::MetaData* ReadEntry::mutable_meta_data(int index) {
  // @@protoc_insertion_point(field_mutable:goby.ReadEntry.meta_data)
  return meta_data_.Mutable(index);
}
inline ::goby::MetaData* ReadEntry::add_meta_data() {
  // @@protoc_insertion_point(field_add:goby.ReadEntry.meta_data)
  return meta_data_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::goby::MetaData >*
ReadEntry::mutable_meta_data() {
  // @@protoc_insertion_point(field_mutable_list:goby.ReadEntry.meta_data)
  return &meta_data_;
}
inline const ::google::protobuf::RepeatedPtrField< ::goby::MetaData >&
ReadEntry::meta_data() const {
  // @@protoc_insertion_point(field_list:goby.ReadEntry.meta_data)
  return meta_data_;
}

// -------------------------------------------------------------------

// MetaData

// required string key = 1;
inline bool MetaData::has_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MetaData::set_has_key() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MetaData::clear_has_key() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MetaData::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_key();
}
inline const ::std::string& MetaData::key() const {
  // @@protoc_insertion_point(field_get:goby.MetaData.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MetaData::set_key(const ::std::string& value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.MetaData.key)
}
inline void MetaData::set_key(const char* value) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.MetaData.key)
}
inline void MetaData::set_key(const char* value, size_t size) {
  set_has_key();
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.MetaData.key)
}
inline ::std::string* MetaData::mutable_key() {
  set_has_key();
  // @@protoc_insertion_point(field_mutable:goby.MetaData.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MetaData::release_key() {
  // @@protoc_insertion_point(field_release:goby.MetaData.key)
  clear_has_key();
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MetaData::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    set_has_key();
  } else {
    clear_has_key();
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:goby.MetaData.key)
}

// required string value = 2;
inline bool MetaData::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MetaData::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MetaData::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MetaData::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_value();
}
inline const ::std::string& MetaData::value() const {
  // @@protoc_insertion_point(field_get:goby.MetaData.value)
  return value_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MetaData::set_value(const ::std::string& value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:goby.MetaData.value)
}
inline void MetaData::set_value(const char* value) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:goby.MetaData.value)
}
inline void MetaData::set_value(const char* value, size_t size) {
  set_has_value();
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:goby.MetaData.value)
}
inline ::std::string* MetaData::mutable_value() {
  set_has_value();
  // @@protoc_insertion_point(field_mutable:goby.MetaData.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MetaData::release_value() {
  // @@protoc_insertion_point(field_release:goby.MetaData.value)
  clear_has_value();
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MetaData::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    set_has_value();
  } else {
    clear_has_value();
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:goby.MetaData.value)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace goby

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Reads_2eproto__INCLUDED
